[project]
name = "starter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "parlant",
    "google-generativeai>=0.3.0",
    "tiktoken",
    "numpy"
]
